@echo off
echo Fixing frontend...

cd frontend

echo Removing node_modules...
rmdir /s /q node_modules 2>nul
del package-lock.json 2>nul

echo Installing rxjs first...
npm install rxjs@~7.8.0

echo Installing Angular core...
npm install @angular/core@^17.0.0 @angular/common@^17.0.0 @angular/router@^17.0.0

echo Installing Angular CLI...
npm install @angular/cli@^17.0.0

echo Installing all dependencies...
npm install

echo Starting development server...
npm start